import { defineConfig } from "wxt";

// https://wxt.dev/api/reference/wxt/interfaces/InlineConfig.html
export default defineConfig({
  srcDir: ".",
  manifestVersion: 3,
  manifest: {
    name: "Toolzzz",
    description: "Extension pour www.fourmizzz.fr.",
    version: "3.0.4",
    // @ts-expect-error AMO refuse la forme objet; Chrome accepte la string. On s'aligne sur Firefox.
    author: "Hraesvelg",
    homepage_url: "https://github.com/GuiEpi/toolzzz",
    browser_specific_settings: {
      gecko: {
        id: "toolzzz@guiepi.github.io",
        strict_min_version: "142.0",
        data_collection_permissions: {
          required: ["none"],
        },
      },
    },
    icons: {
      48: "images/icons/48.png",
      96: "images/icons/96.png",
      128: "images/icons/128.png",
    },
    action: {
      default_icon: "images/icons/48.png",
    },
    permissions: [],
    host_permissions: ["http://*.fourmizzz.fr/*"],
    content_scripts: [
      {
        matches: ["http://*.fourmizzz.fr/*"],
        css: ["css/outiiil.css", "css/toasts.css", "css/datatables.css"],
        js: [
          "js/lib/jquery_3.2.1.js",
          "js/lib/jquery-ui_1.12.1.js",
          "js/lib/jquery-datetimepicker_1.6.3.js",
          "js/lib/jquery-toast_1.3.1.js",
          "js/lib/globalize_0.1.1.js",
          "js/lib/globalize-locale-fr.js",
          "js/lib/clipboard_1.7.1.js",
          "js/lib/highcharts_6.0.7.js",
          "js/lib/highcharts-more.js",
          "js/lib/highcharts-data.js",
          "js/lib/highcharts-stock.js",
          "js/lib/datatables_1.10.16.js",
          "js/lib/numeral_2.0.6.js",
          "js/lib/numeral-locale-fr.js",
          "js/lib/moment_2.19.1.js",
          "js/lib/moment-locale-fr.js",
          "js/lib/moment-duration-format.js",
          "js/class/Utils.js",
          "js/class/Alliance.js",
          "js/class/Armee.js",
          "js/class/Chasse.js",
          "js/class/Combat.js",
          "js/class/Commande.js",
          "js/class/Convoi.js",
          "js/class/Joueur.js",
          "js/class/Parametre.js",
          "js/boite/ComptePlus.js",
          "js/boite/Radar.js",
          "js/boite/Dock.js",
          "js/boite/Boite.js",
          "js/boite/Ponte.js",
          "js/boite/Chasse.js",
          "js/boite/Combat.js",
          "js/boite/Commande.js",
          "js/boite/Parametres.js",
          "js/boite/Rapport.js",
          "js/boite/Rang.js",
          "js/page/Alliance.js",
          "js/page/Armee.js",
          "js/page/Attaquer.js",
          "js/page/Chat.js",
          "js/page/Commerce.js",
          "js/page/Construction.js",
          "js/page/Description.js",
          "js/page/Forum.js",
          "js/page/Laboratoire.js",
          "js/page/Messagerie.js",
          "js/page/Profil.js",
          "js/page/Reine.js",
          "js/page/Ressource.js",
          "js/content.js",
        ],
      },
    ],
    web_accessible_resources: [
      {
        resources: ["images/*", "images/**", "css/*", "js/*"],
        matches: ["http://*.fourmizzz.fr/*"],
      },
    ],
  },
});
